title: Samuel Holmes Project Portfolio
# logo: assets/cropped.png
description: <a href= "/assets/Samuel_Holmes_CV.docx">Click Here to Download My CV</a>
show_downloads: false
theme: jekyll-theme-minimal
