title: Samuel Holmes
#logo: 
#description: This is a portfolio of a handful of notable projects conducted to demonstrate my current skill set to prospective employers. 
#show_downloads: true
theme: jekyll-theme-minimal
