title: Samuel Holmes
logo: /assets/Screenshot 2025-01-23 064108.png 
description: [Click Me To Download Samuel's Current CV](assets/Samuel_Holmes_CV.docx)
#show_downloads: false
theme: jekyll-theme-minimal
